"""
Fase 1.3 — Generar model_data.h (array C para Arduino)
========================================================
Convierte el .tflite a un header C para embeber en el firmware ESP32-S3.

Ejecuta:  python 03_generate_model_header.py

No requiere dependencias adicionales.
"""
import os
import sys

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))
HEADER_PATH = os.path.join(OUTPUT_DIR, "firmware", "src", "model_data.h")

# Buscar TFLite en múltiples ubicaciones posibles.
# El INT8 generado por PTQ es híbrido (pesos INT8 + activaciones float) y la
# librería TFLite Micro usada por el firmware no soporta ese contrato.
TFLITE_CANDIDATES = [
    # Modelo verificado como compatible con TFLite Micro.
    os.path.join(OUTPUT_DIR, "_tf_saved_model", "titan_v4_edge_float32.tflite"),
    # Fallbacks para conversiones futuras compatibles.
    os.path.join(OUTPUT_DIR, "titan_v4_edge_fp32.tflite"),
    os.path.join(OUTPUT_DIR, "_tf_saved_model", "titan_v4_edge_float16.tflite"),
]


def select_tflite_path():
    """Devuelve el primer modelo compatible disponible."""
    for candidate in TFLITE_CANDIDATES:
        if os.path.exists(candidate):
            return candidate
    return None


def tflite_to_c_header(tflite_path, header_path, var_name="titan_model"):
    """Convierte un archivo .tflite a un header C."""
    
    with open(tflite_path, "rb") as f:
        data = f.read()
    
    size_bytes = len(data)
    size_kb = size_bytes / 1024
    size_mb = size_bytes / 1024 / 1024
    
    # Crear directorio si no existe
    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    
    with open(header_path, "w") as f:
        f.write("/**\n")
        f.write(f" * TITAN V4 Edge — TFLite Model Data\n")
        f.write(f" * Auto-generated by 03_generate_model_header.py\n")
        f.write(f" * \n")
        f.write(f" * Source:  {os.path.basename(tflite_path)}\n")
        f.write(f" * Size:    {size_bytes:,} bytes ({size_kb:.1f} KB / {size_mb:.2f} MB)\n")
        f.write(f" * Classes: Primary-9 (rhythm) + Primary-10 (pathology)\n")
        f.write(f" * Input:   [1, 1250, 6] float32 — 10s @ 125Hz, 6 leads\n")
        f.write(f" * Output:  [1, 19] — rhythm_probs(9) + pathology_probs(10)\n")
        f.write(f" *\n")
        f.write(f" * DO NOT EDIT — Regenerate with:\n")
        f.write(f" *   python 03_generate_model_header.py\n")
        f.write(f" */\n\n")
        f.write(f"#ifndef TITAN_MODEL_DATA_H\n")
        f.write(f"#define TITAN_MODEL_DATA_H\n\n")
        f.write(f"#include <cstdint>\n\n")
        f.write(f"// Model stored in flash; runtime preserves PSRAM for tensor arena\n")
        f.write(f"alignas(8) const uint8_t {var_name}_data[] = {{\n")
        
        # Escribir bytes en filas de 16
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {hex_vals},\n")
        
        f.write(f"}};\n\n")
        f.write(f"const unsigned int {var_name}_data_len = {size_bytes};\n\n")
        f.write(f"#endif // TITAN_MODEL_DATA_H\n")
    
    return size_bytes


def main():
    print("=" * 60)
    print("  TFLite → C Header (model_data.h)")
    print("=" * 60)
    
    # Buscar el mejor TFLite disponible
    tflite_path = select_tflite_path()
    
    if tflite_path is None:
        print(f"\n❌ No se encontró ningún archivo TFLite.")
        print(f"   Buscado en:")
        for c in TFLITE_CANDIDATES:
            print(f"     {c}")
        print(f"\n   Ejecuta primero:")
        print(f"   python 01_convert_pth_to_onnx.py")
        print(f"   python 02_convert_onnx_to_tflite.py")
        return False
    
    size_in = os.path.getsize(tflite_path) / 1024 / 1024
    quant = "INT8" if "int8" in tflite_path else "FP32" if "float32" in tflite_path or "fp32" in tflite_path else "FP16"
    print(f"\n[1/2] TFLite {quant}: {size_in:.2f} MB")
    print(f"      {tflite_path}")
    
    print(f"\n[2/2] Generando header C...")
    size_bytes = tflite_to_c_header(tflite_path, HEADER_PATH)
    
    header_size = os.path.getsize(HEADER_PATH) / 1024 / 1024
    print(f"      ✅ Header generado: {header_size:.2f} MB")
    print(f"      {HEADER_PATH}")
    
    # Verificar almacenamiento. El firmware usa el modelo desde Flash para
    # preservar la PSRAM para el tensor arena de TFLite Micro.
    esp32_psram = 8 * 1024 * 1024  # 8 MB
    esp32_flash = 16 * 1024 * 1024  # 16 MB típico
    
    print(f"\n  Compatibilidad ESP32-S3:")
    print(f"    Modelo:        {size_bytes:>10,} bytes ({size_bytes/1024/1024:.2f} MB)")
    print(f"    PSRAM (8MB):   reservada para tensor arena")
    print(f"    Flash (16MB):  {'✅ CABE' if size_bytes < esp32_flash else '❌ NO CABE'}")
    
    # TFLite Micro arena estimada
    arena_estimate = 4 * 1024 * 1024
    total_ram = arena_estimate
    print(f"    Arena est.:    {arena_estimate:>10,} bytes ({arena_estimate/1024/1024:.2f} MB)")
    print(f"    RAM total est: {total_ram:>10,} bytes ({total_ram/1024/1024:.2f} MB)")
    print(f"    {'✅ OK para PSRAM' if total_ram < esp32_psram else '⚠️  Justo, reducir arena si falla'}")
    
    print(f"\n{'=' * 60}")
    print(f"  ✅ HEADER GENERADO — model_data.h listo para Arduino")
    print(f"  Siguiente: Compilar firmware con PlatformIO")
    print(f"{'=' * 60}")
    return True


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
